// GENERATED — do not hand-edit. Included ONLY by the WW implementation TU,
// so its definitions take Impl_ names and the public names belong to the
// dispatcher. The implementation's own source is untouched by this.
#ifndef D_WW_ITEMMDL_IMPL_NAMES_H
#define D_WW_ITEMMDL_IMPL_NAMES_H

#define dWwItemmdl_applyBowMaterialAmbientOnly dWwItemmdlImpl_applyBowMaterialAmbientOnly
#define dWwItemmdl_beginBowDrawScope dWwItemmdlImpl_beginBowDrawScope
#define dWwItemmdl_bracketLog dWwItemmdlImpl_bracketLog
#define dWwItemmdl_clearBowDrawScope dWwItemmdlImpl_clearBowDrawScope
#define dWwItemmdl_clearClothesBundleCache dWwItemmdlImpl_clearClothesBundleCache
#define dWwItemmdl_clearOutlineSuppress dWwItemmdlImpl_clearOutlineSuppress
#define dWwItemmdl_clothesBundleArcName dWwItemmdlImpl_clothesBundleArcName
#define dWwItemmdl_clothesBundleForItem dWwItemmdlImpl_clothesBundleForItem
#define dWwItemmdl_clothesBundleGetTextForMessage dWwItemmdlImpl_clothesBundleGetTextForMessage
#define dWwItemmdl_clothesBundleHandOffset dWwItemmdlImpl_clothesBundleHandOffset
#define dWwItemmdl_clothesBundleHostItem dWwItemmdlImpl_clothesBundleHostItem
#define dWwItemmdl_clothesBundleIconCap dWwItemmdlImpl_clothesBundleIconCap
#define dWwItemmdl_clothesBundleMaxScale dWwItemmdlImpl_clothesBundleMaxScale
#define dWwItemmdl_clothesBundleModelName dWwItemmdlImpl_clothesBundleModelName
#define dWwItemmdl_debugLog dWwItemmdlImpl_debugLog
#define dWwItemmdl_drawWwBowModel dWwItemmdlImpl_drawWwBowModel
#define dWwItemmdl_getClothesBundleModelData dWwItemmdlImpl_getClothesBundleModelData
#define dWwItemmdl_getItemmdlModelData dWwItemmdlImpl_getItemmdlModelData
#define dWwItemmdl_getVbowModelData dWwItemmdlImpl_getVbowModelData
#define dWwItemmdl_isClothesGetPresentation dWwItemmdlImpl_isClothesGetPresentation
#define dWwItemmdl_isPhase2BracketBow dWwItemmdlImpl_isPhase2BracketBow
#define dWwItemmdl_log2QPrimeAudit dWwItemmdlImpl_log2QPrimeAudit
#define dWwItemmdl_logHeap dWwItemmdlImpl_logHeap
#define dWwItemmdl_logShapeInventory dWwItemmdlImpl_logShapeInventory
#define dWwItemmdl_logTevOrderDump dWwItemmdlImpl_logTevOrderDump
#define dWwItemmdl_patchModelForPc dWwItemmdlImpl_patchModelForPc
#define dWwItemmdl_retainItemmdlArcOnDemoItemDelete dWwItemmdlImpl_retainItemmdlArcOnDemoItemDelete
#define dWwItemmdl_setWwBowActorAmbient dWwItemmdlImpl_setWwBowActorAmbient
#define dWwItemmdl_setWwBowGetItemBeamSuppress dWwItemmdlImpl_setWwBowGetItemBeamSuppress
#define dWwItemmdl_shouldSuppressGetItemBeamParticle dWwItemmdlImpl_shouldSuppressGetItemBeamParticle
#define dWwItemmdl_stepPrivateItemmdlArcLoad dWwItemmdlImpl_stepPrivateItemmdlArcLoad
#define dWwItemmdl_tickHeldBowArcMount dWwItemmdlImpl_tickHeldBowArcMount
#define dWwItemmdl_use2DIsolateHeap dWwItemmdlImpl_use2DIsolateHeap
#define dWwItemmdl_usingCustomHeldModel dWwItemmdlImpl_usingCustomHeldModel
#define dWwItemmdl_writeClothesBundleIconTimg dWwItemmdlImpl_writeClothesBundleIconTimg

#endif
