#ifndef D_EXT_PLUGIN_WW_ITEMMDL_DISPATCH_H
#define D_EXT_PLUGIN_WW_ITEMMDL_DISPATCH_H

// ============================================================================
// Step 19 cluster 2 — dWwItemmdl, 35 entry points across 12 receiver TUs.
//
// WHY A DISPATCH TABLE RATHER THAN THE CLUSTER-1 TREATMENT
// Cluster 1 was DATA: one positional table, one lookup, one interposition. This
// cluster is CODE: 35 free functions the receiver calls directly. There is no
// single lookup to interpose on, so the seam has to be the call itself.
//
// Every function keeps its name and every one of the ~90 call sites is
// untouched. What changes is where the name resolves: to a dispatcher that
// forwards to the WW layer when present, and returns a NOT-APPLICABLE value
// when absent. The receiver therefore links and runs with no WW layer at all,
// which is the plugin contract -- host works alone, plugin adds.
//
// The defaults are safe by inspection because the API's return types say so:
//   void          -> do nothing        bool  -> false (not a WW case)
//   pointer       -> NULL              scalar -> 0
// None of them fabricates a value the receiver could mistake for real data.
//
// GENERATED, not transcribed. 35 signatures is past the point where hand-copying
// is honest work -- this session has already paid twice for transcription error
// (a dropped profile row, an uppercase-only regex). The generator reads the
// header and the linker's own unresolved list, so the set cannot drift from
// what the build actually needs.
// ============================================================================

#include "d/d_ww_itemmdl_pc.h"

// GENERATED by tools/foundry/gen_itemmdl_dispatch.py — do not hand-edit.
// One field per WW itemmdl entry point. NULL means the WW layer is absent.
struct WwItemmdlApi {
    void (*applyBowMaterialAmbientOnly)(J3DModel* model, dKy_tevstr_c* tevstr_p);
    void (*beginBowDrawScope)(J3DModel* model, fpc_ProcID owner_id);
    void (*bracketLog)(const char* message);
    void (*clearBowDrawScope)();
    void (*clearClothesBundleCache)();
    void (*clearOutlineSuppress)();
    const char* (*clothesBundleArcName)();
    bool (*clothesBundleForItem)(u8 item_no);
    const char* (*clothesBundleGetTextForMessage)(u32 msg_id);
    bool (*clothesBundleHandOffset)(f32* out_x, f32* out_y, f32* out_z);
    u8 (*clothesBundleHostItem)();
    u32 (*clothesBundleIconCap)(u8 item_no);
    f32 (*clothesBundleMaxScale)();
    const char* (*clothesBundleModelName)();
    void (*debugLog)(const char* message);
    void (*drawWwBowModel)(J3DModel* model);
    J3DModelData* (*getClothesBundleModelData)();
    J3DModelData* (*getItemmdlModelData)(u16 bdl_index);
    J3DModelData* (*getVbowModelData)(const char* arc_name);
    bool (*isClothesGetPresentation)();
    bool (*isPhase2BracketBow)(u8 item_no);
    void (*log2QPrimeAudit)(const char* tag, J3DModelData* model_data, s32 room_no);
    void (*logHeap)(const char* label);
    void (*logShapeInventory)(J3DModelData* model_data, const char* phase);
    void (*logTevOrderDump)(J3DModelData* model_data, const char* phase, s32 room_no, bool log_gx_runtime);
    void (*patchModelForPc)(J3DModelData* model_data);
    bool (*retainItemmdlArcOnDemoItemDelete)();
    void (*setWwBowActorAmbient)(dKy_tevstr_c* tevstr_p);
    void (*setWwBowGetItemBeamSuppress)(bool suppress);
    bool (*shouldSuppressGetItemBeamParticle)(u16 particle_id);
    int (*stepPrivateItemmdlArcLoad)(request_of_phase_process_class* phase);
    void (*tickHeldBowArcMount)();
    bool (*use2DIsolateHeap)();
    bool (*usingCustomHeldModel)(J3DModel* i_model);
    bool (*writeClothesBundleIconTimg)(u8 item_no, void* out_buf, u32 out_cap);
    // The namespaced editor/dev trio from d_ww_itemmdl_test.h. Same cluster,
    // different header, so the generator did not see them.
    void (*requestBowGetItemDemoReplay)();
    void (*tickBowGetItemDemoReplay)();
    const char* (*getBowGetItemDemoReplayStatus)();
};

// The live table. All-NULL means "no WW layer", which is the state a stock
// dusklight.exe ships in.
extern WwItemmdlApi g_wwItemmdlApi;

// Fills every field. Defined WW-side, so excluding the WW layer removes it and
// the table stays NULL -- the absence is structural, not a runtime flag.
void dWwItemmdlDispatch_install();

// Non-NULL fields, for diagnostics and for the boot log to state plainly
// whether the layer is present.
int dWwItemmdlDispatch_boundCount();

#endif  // D_EXT_PLUGIN_WW_ITEMMDL_DISPATCH_H
