#ifndef D_EXT_PLUGIN_WW_NPCMOUNT_DISPATCH_H
#define D_EXT_PLUGIN_WW_NPCMOUNT_DISPATCH_H

// ============================================================================
// Step 19 cluster 3 — dExtNpcMount, 36 entry points across 17 receiver TUs.
//
// Same shape as cluster 2 and deliberately so: the pattern is the deliverable,
// not the individual cluster. Every function keeps its name and every call site
// is untouched; what changes is where the name resolves.
//
// Defaults are safe by inspection from the return types -- void does nothing,
// bool is false ("no mount involved"), pointers are NULL, scalars 0. The
// receiver therefore links and runs with no WW layer, which is the plugin
// contract: host works alone, plugin adds.
//
// GENERATED by tools/foundry/gen_cluster_dispatch.py from TWO inputs that must
// agree -- the linker's unresolved list and the header's declarations. A symbol
// in one and not the other is reported, never guessed at.
// ============================================================================

#include "d/d_ext_npc_mount.h"

struct WwNpcMountApi {
    J3DModelData* (*fn_acquireDemoModel)(const char* arc, u16 id, void* res);
    J3DModelData* (*fn_acquireModelData)(const char* arc, const char* modelName);
    void (*fn_cancelTransports)();
    bool (*fn_consumeForcedCreateProc)(char* procOut, u32 procOutBytes);
    int (*fn_create)(dExtNpcMount_c* i_this, const char* procName);
    bool (*fn_cycleHeadNearest)(const cXyz& from, f32 maxDist);
    int (*fn_delete)(dExtNpcMount_c* i_this);
    int (*fn_draw)(dExtNpcMount_c* i_this);
    void (*fn_endDoorDemoLock)();
    int (*fn_execute)(dExtNpcMount_c* i_this);
    void (*fn_forceNextAttach)(const char* modelName, const char* jointName);
    void (*fn_forceNextSpawnSrc)(const char* src);
    bool (*fn_hasPayload)(const char* procName);
    bool (*fn_hasSocketPayload)(const char* socketName);
    bool (*fn_isRoomLaneProtected)(int roomNo);
    bool (*fn_isRoomLaneRoom)(int roomNo);
    bool (*fn_lookup)(const char* procName, dExtNpcManifest* out);
    const char* (*fn_nearestDisplayName)(const cXyz& from, f32 maxDist);
    void (*fn_onRoomObjectsReady)(const char* stageName, int roomNo);
    void (*fn_onRoomUnload)(const char* stageName, int roomNo);
    void (*fn_onStageReady)();
    void (*fn_pollBgWarps)();
    void (*fn_pollCullProbe)();
    void (*fn_pollIdentifyProbe)();
    void (*fn_pollRegionTriggers)();
    bool (*fn_providerAt)(int index, dExtNpcManifest* out);
    int (*fn_providerCount)();
    bool (*fn_queryActor)(const fopAc_ac_c* actor, dExtNpcIdentifyInfo* out);
    void (*fn_registerRoomLane)(const char* procName, int hostRoom);
    bool (*fn_requestBgWarp)(const char* procName);
    void (*fn_rescanProviders)();
    bool (*fn_resolveSocket)(const char* socketName, int arg, char* procOut, u32 procOutBytes);
    bool (*fn_setDisplayNameNearest)(const cXyz& from, f32 maxDist, const char* name);
    bool (*fn_shouldSkipBtp)(const char* arcName);
    s16 (*fn_socketActorId)(const char* socketName);
    bool (*fn_takePendingSpawn)(fpc_ProcID id, char* procOut, u32 procBytes, char* srcOut, u32 srcBytes, char* headOut, u32 headBytes, char* jointOut, u32 jointBytes);
};

extern WwNpcMountApi g_wwNpcMountApi;

// Defined WW-side, so excluding the layer removes it and the table stays NULL.
void dWwNpcMountDispatch_install();
int dWwNpcMountDispatch_boundCount();

#endif
