// GENERATED. Included ONLY by the WW implementation TU.
#ifndef D_WW_NPCMOUNT_IMPL_NAMES_H
#define D_WW_NPCMOUNT_IMPL_NAMES_H

#define dExtNpcMount_acquireDemoModel dExtNpcMount_Impl_acquireDemoModel
#define dExtNpcMount_acquireModelData dExtNpcMount_Impl_acquireModelData
#define dExtNpcMount_cancelTransports dExtNpcMount_Impl_cancelTransports
#define dExtNpcMount_consumeForcedCreateProc dExtNpcMount_Impl_consumeForcedCreateProc
#define dExtNpcMount_create dExtNpcMount_Impl_create
#define dExtNpcMount_cycleHeadNearest dExtNpcMount_Impl_cycleHeadNearest
#define dExtNpcMount_delete dExtNpcMount_Impl_delete
#define dExtNpcMount_draw dExtNpcMount_Impl_draw
#define dExtNpcMount_endDoorDemoLock dExtNpcMount_Impl_endDoorDemoLock
#define dExtNpcMount_execute dExtNpcMount_Impl_execute
#define dExtNpcMount_forceNextAttach dExtNpcMount_Impl_forceNextAttach
#define dExtNpcMount_forceNextSpawnSrc dExtNpcMount_Impl_forceNextSpawnSrc
#define dExtNpcMount_hasPayload dExtNpcMount_Impl_hasPayload
#define dExtNpcMount_hasSocketPayload dExtNpcMount_Impl_hasSocketPayload
#define dExtNpcMount_isRoomLaneProtected dExtNpcMount_Impl_isRoomLaneProtected
#define dExtNpcMount_isRoomLaneRoom dExtNpcMount_Impl_isRoomLaneRoom
#define dExtNpcMount_lookup dExtNpcMount_Impl_lookup
#define dExtNpcMount_nearestDisplayName dExtNpcMount_Impl_nearestDisplayName
#define dExtNpcMount_onRoomObjectsReady dExtNpcMount_Impl_onRoomObjectsReady
#define dExtNpcMount_onRoomUnload dExtNpcMount_Impl_onRoomUnload
#define dExtNpcMount_onStageReady dExtNpcMount_Impl_onStageReady
#define dExtNpcMount_pollBgWarps dExtNpcMount_Impl_pollBgWarps
#define dExtNpcMount_pollCullProbe dExtNpcMount_Impl_pollCullProbe
#define dExtNpcMount_pollIdentifyProbe dExtNpcMount_Impl_pollIdentifyProbe
#define dExtNpcMount_pollRegionTriggers dExtNpcMount_Impl_pollRegionTriggers
#define dExtNpcMount_providerAt dExtNpcMount_Impl_providerAt
#define dExtNpcMount_providerCount dExtNpcMount_Impl_providerCount
#define dExtNpcMount_queryActor dExtNpcMount_Impl_queryActor
#define dExtNpcMount_registerRoomLane dExtNpcMount_Impl_registerRoomLane
#define dExtNpcMount_requestBgWarp dExtNpcMount_Impl_requestBgWarp
#define dExtNpcMount_rescanProviders dExtNpcMount_Impl_rescanProviders
#define dExtNpcMount_resolveSocket dExtNpcMount_Impl_resolveSocket
#define dExtNpcMount_setDisplayNameNearest dExtNpcMount_Impl_setDisplayNameNearest
#define dExtNpcMount_shouldSkipBtp dExtNpcMount_Impl_shouldSkipBtp
#define dExtNpcMount_socketActorId dExtNpcMount_Impl_socketActorId
#define dExtNpcMount_takePendingSpawn dExtNpcMount_Impl_takePendingSpawn

#endif
