#!/usr/bin/env python3
"""gen_tsubo_data.py — tsubo port step 1 (the gen_item_data.py pattern).

Extracts the DONOR's daTsubo static tables — M_arcname[16], M_cyl_src,
M_data[16] (0xCC/row), M_data_spec_boko, M_attrSpine — re-emitting initializer
tokens VERBATIM with symbolic identifiers (JA_SE_*, DataFlag, dCcD/dCcG enums,
AT_TYPE_*) resolved to literals from the donor's own headers, donor names kept
as comments. Zero hand transcription (traps #1/#2/#6).

Usage: python gen_tsubo_data.py [--out <path>]
"""
import argparse
import re
import sys
from pathlib import Path

DONOR = Path(r"D:/XXXXXXX/WW DP")
TU = DONOR / "src/d/actor/d_a_tsubo.cpp"


def build_symbol_table():
    """Resolve donor symbolic constants to numeric literals."""
    syms = {}
    # JA_SE ids
    for hdr in [DONOR / "include/JAZelAudio/JAISeMgr.h",
                DONOR / "include/JAZelAudio/JAIZelBasic.h"]:
        if hdr.exists():
            t = hdr.read_text(errors="replace")
            for m in re.finditer(r"(JA_SE_[A-Za-z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)", t):
                syms[m.group(1)] = int(m.group(2), 0)
    # broad sweep for JA_SE if not found above
    if not any(k.startswith("JA_SE_") for k in syms):
        for hdr in (DONOR / "include").rglob("*.h"):
            t = hdr.read_text(errors="replace")
            if "JA_SE_" in t:
                for m in re.finditer(r"(JA_SE_[A-Za-z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)", t):
                    syms[m.group(1)] = int(m.group(2), 0)
    # cc/at enums + DataFlag from known headers
    for rel in ["include/d/d_cc_d.h", "include/SSystem/SComponent/c_cc_d.h",
                "include/d/actor/d_a_tsubo.h"]:
        p = DONOR / rel
        if p.exists():
            t = p.read_text(errors="replace")
            cur = None
            for line in t.splitlines():
                m = re.search(r"([A-Za-z_][A-Za-z0-9_]*_e|DATA_FLAG_[0-9A-Fa-f]+_e|AT_TYPE_[A-Za-z0-9_]+)\s*=\s*"
                              r"(\(?\s*1\s*<<\s*(\d+)\s*\)?|0x[0-9A-Fa-f]+|\d+)", line)
                if m:
                    if m.group(3) is not None:
                        syms[m.group(1)] = 1 << int(m.group(3))
                    else:
                        syms[m.group(1)] = int(m.group(2).strip("()"), 0)
    return syms


def extract_table(text, decl, end_marker="\n};"):
    i = text.index(decl)
    j = text.index(end_marker, i)
    return text[i:j + len(end_marker)]


def resolve_expr(tok, syms):
    """Resolve a token that may be an OR/AND-NOT expression of symbols."""
    tok = tok.strip().strip("{}").strip()
    # strip enum casts: (DataFlag_e)(...) -> (...)
    tok = re.sub(r"^\((?:daTsubo::)?[A-Za-z_][A-Za-z0-9_:]*_e\)\s*", "", tok).strip()
    if tok.startswith("(") and tok.endswith(")"):
        tok = tok[1:-1].strip()
    # DEMO_SELECT(a, b) -> b (retail law), then resolve b
    m = re.match(r"DEMO_SELECT\(\s*([^,]+),\s*(.+?)\s*\)$", tok)
    if m:
        tok = m.group(2).strip()
    if re.fullmatch(r"-?\d+\.?\d*f?|0x[0-9A-Fa-f]+|-?\.\d+f?", tok):
        return tok, None
    if tok in syms:
        return f"0x{syms[tok]:X}", tok
    # expression of symbols: A | B, A & ~B, DEMO_SELECT(...)
    expr = tok
    names = re.findall(r"[A-Za-z_][A-Za-z0-9_]*", tok)
    ok = True
    for n in set(names):
        if n in ("DEMO_SELECT",):
            # retail law: second argument
            m = re.match(r'DEMO_SELECT\(\s*"[^"]*"\s*,\s*"([^"]*)"\s*\)', tok)
            if m:
                return f'"{m.group(1)}"', tok
            ok = False
            break
        if n in syms:
            expr = re.sub(rf"\b{n}\b", str(syms[n]), expr)
        else:
            ok = False
            break
    if ok:
        try:
            val = eval(expr.replace("~", " ~"), {"__builtins__": {}})
            return f"0x{val & 0xFFFFFFFF:X}", tok
        except Exception:
            pass
    return None, tok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out")
    args = ap.parse_args()

    text = TU.read_text(errors="replace")
    # retail law on DEMO forks
    text = re.sub(r"#if VERSION == VERSION_DEMO.*?#else(.*?)#endif", r"\1", text, flags=re.S)
    text = re.sub(r"#if VERSION == VERSION_DEMO.*?#endif", "", text, flags=re.S)
    text = re.sub(r"#if VERSION > VERSION_DEMO(.*?)#endif", r"\1", text, flags=re.S)

    syms = build_symbol_table()
    # dRes indices from the assets headers (gen_item_data's sweep)
    for h in (DONOR / "assets/GZLE01/res").rglob("*.h"):
        t = h.read_text(errors="replace")
        for m in re.finditer(r"(dRes_INDEX_[A-Za-z0-9_]+_e)\s*=\s*(0x[0-9A-Fa-f]+|\d+)", t):
            syms[m.group(1)] = int(m.group(2), 0)
    print(f"symbols resolved: {len(syms)} (JA_SE: "
          f"{sum(1 for k in syms if k.startswith('JA_SE_'))})", file=sys.stderr)

    out = []
    out.append("// GENERATED by gen_tsubo_data.py from DONOR d_a_tsubo.cpp (retail branch).")
    out.append("// Do not hand-edit — regenerate. (tsubo port step 1)")
    out.append("// KIT-LINEAGE: native-port (generated donor data)")
    out.append("")

    # arcnames — verbatim strings
    arct = extract_table(text, "const char* const Act_c::M_arcname[] = {")
    # DEMO_SELECT("a","b") -> "b" (retail) before the string sweep
    arct = re.sub(r'DEMO_SELECT\(\s*"[^"]*"\s*,\s*"([^"]*)"\s*\)', r'"\1"', arct)
    names = re.findall(r'"([^"]+)"', arct)
    out.append(f"static const char* const l_wwTsuboArcname[{len(names)}] = {{")
    for n in names:
        out.append(f'    "{n}",')
    out.append("};")
    out.append("")
    print(f"arcnames: {len(names)}", file=sys.stderr)

    # M_data rows: capture each top-level { ... } row inside the table
    dt = extract_table(text, "const Act_c::Data_c Act_c::M_data[] = {")
    body = dt[dt.index("{", dt.index("[]")) + 1: dt.rindex("};")]
    rows, depth, cur = [], 0, ""
    for ch in body:
        if ch == "{":
            depth += 1
            if depth == 1:
                cur = ""
                continue   # outermost brace stripped
        if ch == "}":
            depth -= 1
            if depth == 0:
                rows.append(cur)
                continue   # outermost brace stripped
        if depth >= 1:
            cur += ch      # inner braces KEPT (donor grouping is the init shape)
    print(f"M_data rows: {len(rows)}", file=sys.stderr)
    unresolved = 0

    def subst_symbols(row_text):
        """In-place symbol substitution on donor-verbatim row text."""
        nonlocal unresolved
        t = re.sub(r"//[^\n]*", "", row_text)
        # DEMO_SELECT(a,b) -> b
        t = re.sub(r"DEMO_SELECT\(\s*[^,]+,\s*([^)]+)\)", r"\1", t)
        # strip enum casts
        t = re.sub(r"\((?:daTsubo::)?[A-Za-z_][A-Za-z0-9_:]*_e\)", "", t)

        def repl(m):
            nonlocal unresolved
            name = m.group(0)
            if name in syms:
                return f"0x{syms[name]:X}/*{name}*/"
            if name in ("f", "e"):
                return name
            unresolved += 1
            return f"/*UNRESOLVED:{name}*/0"

        t = re.sub(r"\b[A-Za-z_][A-Za-z0-9_]*\b(?!\s*\()", repl, t)
        return t

    out.append(f"static const WwTsuboData l_wwTsuboData[{len(rows)}] = {{")
    for ridx, raw in enumerate(rows):
        out.append(f"    {{ // subtype {ridx} ('{names[ridx] if ridx < len(names) else '?'}')")
        out.append(subst_symbols(raw).strip().rstrip(","))
        out.append("    },")
    out.append("};")
    out.append("")

    # spec boko + attrSpine — verbatim numeric tables
    for decl, nm in [("const Act_c::SpecBokoData Act_c::M_data_spec_boko[] = {",
                      "l_wwTsuboSpecBoko"),
                     ("const Act_c::AttrSpine_c Act_c::M_attrSpine = {",
                      "l_wwTsuboAttrSpine")]:
        try:
            t = extract_table(text, decl)
            inner = t[t.index("{", len(decl) - 2):]
            out.append(f"// donor: {decl.split('=')[0].strip()}")
            out.append(t.replace("Act_c::SpecBokoData Act_c::M_data_spec_boko",
                                 f"WwTsuboSpecBoko {nm}")
                        .replace("Act_c::AttrSpine_c Act_c::M_attrSpine",
                                 f"WwTsuboAttrSpine {nm}")
                        .replace("const Act_c::", "static const "))
            out.append("")
        except ValueError:
            print(f"table absent: {decl[:40]}", file=sys.stderr)

    print(f"unresolved tokens: {unresolved}", file=sys.stderr)
    if args.out:
        Path(args.out).write_text("\n".join(out), encoding="utf-8")
        print(f"wrote {args.out}", file=sys.stderr)
    return 0 if unresolved == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
