#!/usr/bin/env python3
"""gen_objectname_data.py — R5 absorption item 2 (tale §853/§855).

Parses the DONOR's own l_objectName table (WW DP src/d/d_stage.cpp OBJNAME
rows) and emits tools/conversion_db_objectname.py: the name→(procname, subtype,
gba) join key as LAW-tier R5 facts, donor-verbatim, many-to-one preserved
(the NAME is the key; procnames repeat freely).

The same table serves §853 item 6 (the placement-weighted ceiling-metric
join). The runtime seam (dStage_searchName hook) stays L8/Housing — this is
the DATA half only.

Regenerate (never hand-edit the output):
    python tools/ww_crew_restoration_skeleton/gen_objectname_data.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

DONOR = Path(r"D:/XXXXXXX/WW DP/src/d/d_stage.cpp")
OUT = Path(__file__).resolve().parents[1] / "conversion_db_objectname.py"

ROW = re.compile(
    r'OBJNAME\(\s*"([^"]+)"\s*,\s*(fpcNm_[A-Za-z0-9_]+_e)\s*,\s*(\d+)\s*,\s*'
    r'(\d+|DEMO_SELECT\(\s*\d+\s*,\s*\d+\s*\))\s*\)'
)
DEMO_SEL = re.compile(r'DEMO_SELECT\(\s*(\d+)\s*,\s*(\d+)\s*\)')


def gba_retail(tok: str) -> str:
    # retail law: DEMO_SELECT(demo, retail) -> retail (the gen_item/gen_tsubo rule)
    m = DEMO_SEL.match(tok)
    return m.group(2) if m else tok


def main() -> int:
    text = DONOR.read_text(encoding="utf-8", errors="replace")
    rows = ROW.findall(text)
    if not rows:
        print("no OBJNAME rows parsed — donor path or macro shape changed", file=sys.stderr)
        return 1

    dupes = len(rows) - len({name for name, *_ in rows})
    lines = [
        '"""GENERATED by gen_objectname_data.py — do not hand-edit.',
        "",
        "R5 join key (tale §853 item 2 / §855): the DONOR's l_objectName table,",
        "WW DP src/d/d_stage.cpp, donor-verbatim. name -> (procname, subtype, gba).",
        "Many-to-one preserved: names are keys, procnames repeat.",
        '"""',
        "",
        "# Each value: ((procname, subtype, gba), tier, why) — consumed by",
        "# conversion_db.Fact via the loader there (kept dependency-free here).",
        "OBJECT_NAME_ROWS = {",
    ]
    for name, proc, sub, gba in rows:
        lines.append(f'    "{name}": ("{proc}", {sub}, {gba_retail(gba)}),')
    lines += [
        "}",
        "",
        f"ROW_COUNT = {len(rows)}",
        f"DUPLICATE_NAME_COUNT = {dupes}  # donor duplicates, kept last-wins like the donor walk",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"emitted {OUT.name}: {len(rows)} rows ({dupes} duplicate names)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
