#!/usr/bin/env python3
# ============================================================================
# backlog.py — the BACKLOG SURFACE (CALLS row, user-requested, tale §881).
#
# THE MISS IT FIXES: a port blocked on an unported system landed in
# BUILD-QUEUE's HELD section as PROSE, and its promotion when the blocker
# cleared depended on someone remembering. RES-LIFETIME-DEMO's move released
# 134 TUs and the release was INVISIBLE until the gate was re-run by hand.
#
# WHAT IT IS: blocked-ports x blocking-system, GENERATED never hand-kept
# (the three-times-independently-discovered doctrine: no human ever types a
# status). Blocked rows are DECLARED with receipts (like every registry in
# this estate); system status comes live from port_deps.SYSTEMS; the wider
# demand context comes from --unlocks corpus scans.
#
# THE PROMOTION RULE (standing, printed in the artifact): when a system's
# registry status moves green (PORTED / DESCENDANT / EQUIVALENT-RETAIL), every
# port it held moves to **PRIORITY — ahead of fresh ports at the head of
# PORT-QUEUE**, and this artifact's RELEASED section names them until they
# land. Regenerate after ANY registry move; the release can no longer be
# invisible.
#
# Usage: backlog.py            (regenerates docs/state/ww-staging/BACKLOG.md)
# Read-only except the artifact. Exit 0.
# ============================================================================
import sys
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(HERE))
import port_deps

GREEN = ("PORTED", "DESCENDANT", "EQUIVALENT-RETAIL")

# ---------------------------------------------------------------------------
# BLOCKED PORTS — DECLARED with receipts. A row leaves this table only when
# the port LANDS (not when it unblocks — the RELEASED section tracks that gap).
# ---------------------------------------------------------------------------
BLOCKED = {
    "d_a_lwood": {
        "systems": ["WW-WIND"],
        "receipt": "LINK-VERIFIED (CALLS return): dKyWw_get_wind_vec / "
                   "dKyWw_get_wind_pow / dKyWw_pntwind_get_info unresolved — "
                   "the port correctly calls WW's API; the field must land.",
    },
    "d_a_obj_lpalm": {
        "systems": ["WW-WIND"],
        "receipt": "Gate HOLD (tale §869) + own verbatim marker "
                   "(1 Nonmatching on _execute, user ruling: not verbatim, "
                   "not passed) — TWO holds, both must clear.",
    },
    "d_a_npc_p1": {
        "systems": ["WW-DEMO-CAMERA"],
        "receipt": "2nd pull (CALLS return): SkipSmoother, 3-arg "
                   "setNextStage, dDemo_actor_c, ENABLE_TRANS/ROTATE_e — "
                   "demo/camera surfaces, not actor fixes.",
    },
}


def main():
    lines = []
    lines.append("# BACKLOG — blocked ports x blocking system (GENERATED by "
                 "backlog.py; never hand-edit)")
    lines.append("")
    lines.append("> **PROMOTION RULE (standing):** when a system's registry status moves")
    lines.append("> green (PORTED / DESCENDANT / EQUIVALENT-RETAIL), every port it held")
    lines.append("> becomes **PRIORITY — ahead of fresh ports at the head of PORT-QUEUE** —")
    lines.append("> and appears in RELEASED below until it lands. Regenerate after ANY")
    lines.append("> registry move: `python tools/foundry/backlog.py`.")
    lines.append("")

    # ---- blocked + released, computed live against the registry ----
    still, released = [], []
    for port, row in BLOCKED.items():
        held_on = [s for s in row["systems"]
                   if port_deps.SYSTEMS.get(s, {}).get("status") not in GREEN]
        if held_on:
            still.append((port, held_on, row))
        else:
            released.append((port, row))

    lines.append("## RELEASED — blockers cleared, port to the queue head NOW")
    lines.append("")
    if released:
        for port, row in released:
            lines.append("- **%s** — all blocking systems green. PRIORITY. (%s)"
                         % (port, row["receipt"]))
    else:
        lines.append("- (none — every declared blocked port still has an open blocker)")
    lines.append("")

    lines.append("## BLOCKED — port x system, with the system's live status")
    lines.append("")
    for port, held_on, row in sorted(still):
        for s in held_on:
            st = port_deps.SYSTEMS[s]["status"]
            lines.append("- **%s** held on **%s** [%s]" % (port, s, st))
        lines.append("    %s" % row["receipt"])
    lines.append("")

    lines.append("## SYSTEMS — status + measured demand (donor corpus --unlocks)")
    lines.append("")
    for name, row in port_deps.SYSTEMS.items():
        if row["status"] in GREEN:
            lines.append("- %s [%s] — green; holds nothing" % (name, row["status"]))
            continue
        users = []
        for fp in sorted(port_deps.DONOR_ACTOR_SRC.glob("d_a_*.cpp")):
            toks = set(port_deps.RE_TOKEN.findall(port_deps.strip_comments(
                fp.read_text(encoding="utf-8", errors="replace"))))
            if any(sig in toks for sig in row["signatures"]):
                users.append(fp.stem)
        lines.append("- **%s** [%s] — holds %d donor TU(s) corpus-wide"
                     % (name, row["status"], len(users)))
        lines.append("    unlocks on green: %s%s"
                     % (", ".join(users[:10]), " …" if len(users) > 10 else ""))
    lines.append("")

    out = REPO / "docs" / "state" / "ww-staging" / "BACKLOG.md"
    out.write_text("\r\n".join(lines), encoding="utf-8", newline="")
    print("\n".join(lines[:40]))
    print("... -> %s" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
