#!/usr/bin/env python3
# ============================================================================
# binding_plan.py — roadmap step 15 deliverable: classify every host import the
# WW layer makes into how a PREBUILT PLUGIN would reach it.
#
# Distribution is ruled (A): a prebuilt plugin, standalone, loadable into any
# dusklight build (§518). We design no ABI — dusklight ships one. What we owe is
# the BINDING PLAN (§519):
#
#   (a) SERVICE   — a published SDK service in sdk/include/mods/svc/*.h.
#                   Versioned and negotiated; survives updates by contract.
#   (b) LINK      — present in the curated export surface (dusklight_exports.def)
#                   so the import library resolves it at LINK time. A direct
#                   call, no hook. Windows path.
#   (c) RESOLVE   — not exported, but reachable by name through the hook
#                   service's resolve() against the embedded symbol manifest
#                   (file-local statics included: HOOK_SYMBOL_LOCAL).
#   (e) COMPILE-IN — a macro or an inline/template body. NOT a symbol at all:
#                   it compiles into the caller, so a plugin including the same
#                   header simply has it. Omitting this bucket inflated the
#                   "long pole" from 29 symbols to 772 (§520).
#
# WHY THE .def IS THE RIGHT ORACLE, AND WHERE IT STOPS
# The export surface is GENERATED by symgen at build time from the built objects
# (cmake/WindowsExports.cmake), so it is the build's own statement about what is
# linkable -- not a hand list, which is the failure mode the Tier-1 strip set
# already taught us. It cannot answer (c): the embedded symbol manifest lives
# inside the linked executable and needs the running image. So a symbol absent
# here is reported UNRESOLVED-HERE, never "unreachable" -- №31-C.
#
# Read-only. Usage: binding_plan.py [--def PATH] [--misses]
# ============================================================================
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import census_axis_c as C  # noqa: E402
import census_axis_p as P  # noqa: E402
import census_axis_w as W  # noqa: E402
import ww_census as WC  # noqa: E402

DEF = C.REPO / "build/windows-msvc-relwithdebinfo/dusklight_exports.def"
SDK = C.REPO / "sdk/include/mods"

# MSVC decoration: `?ident@scope@@...` for C++, bare `ident` for extern "C".
#
# The first form of this pattern DROPPED EVERY CONSTRUCTOR AND DESTRUCTOR.
# MSVC encodes special names as `??<code>Name@` -- `??0mDoExt_McaMorfSO@@...` for
# a constructor -- so the digit sitting between `??` and the name broke a match
# that expected an identifier there. The effect was one-directional and
# flattering in the wrong direction: five constructor calls were reported as
# NEEDING resolve() when they are exported and directly linkable. Caught by
# grepping the .def for a name the tool had just classified as absent, which is
# the only reason it did not ship.
MANGLED = re.compile(r"^\?\?[$_0-9A-Z]?([A-Za-z_]\w*)@"      # ctor/dtor/template
                     r"|^\?([A-Za-z_]\w*)@")                  # ordinary
PLAIN = re.compile(r"^([A-Za-z_]\w*)$")
# A C declaration in an SDK header: `ret (*name)(...)` or `ret name(...)`.
SDK_FN = re.compile(r"[A-Za-z_]\w*\s*\**\s*\(?\*?\s*([A-Za-z_]\w*)\s*\)?\s*\(", re.M)


def exported_identifiers(path):
    """Identifier set from the generated export surface.

    Matching is by IDENTIFIER, not by full decorated name: the census records a
    call as `dComIfGp_getPlayer`, while the .def carries the full MSVC
    decoration. Overloads therefore collapse to one identifier -- which is the
    right granularity for "can a plugin reach this name at all", and the wrong
    one for "which overload", a question this artifact does not claim to answer.
    """
    if not path.is_file():
        return None
    out = set()
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        tok = line.strip().split()
        if not tok or tok[0] == "EXPORTS":
            continue
        m = MANGLED.match(tok[0])
        if m:
            out.add(m.group(1) or m.group(2))
        elif PLAIN.match(tok[0]):
            out.add(tok[0])
    return out


def sdk_service_symbols():
    """Function names published by the SDK's C service headers."""
    out = set()
    if not SDK.is_dir():
        return out
    for h in SDK.rglob("*.h"):
        txt = h.read_text(encoding="utf-8", errors="replace")
        txt = re.sub(r"/\*.*?\*/", " ", txt, flags=re.S)
        txt = re.sub(r"//[^\n]*", " ", txt)
        for m in SDK_FN.finditer(txt):
            out.add(m.group(1))
    return out - {"if", "for", "while", "switch", "sizeof", "return", "defined"}


# ============================================================================
# ARTIFACT CLASSIFICATION (19a, tale §950) — the (c) set is the number this
# project calls "the real long pole", so it must count REAL host imports and
# nothing else. Verified by reading every entry the manifest called MISSING:
#   emplace_back  std::vector member  (the plugin links its own STL)
#   good          matched inside COMMENT PROSE ("only as good as")
#   field_0x0     a decomp FIELD NAME inside a comment
#   sp54          a LOCAL VARIABLE  (cXyz sp54; d_bg_s.cpp:769)
#   msg           matched inside COMMENT PROSE
#   ModuleProlog  console REL prolog, named only in a comment; dead on PC
#   ModuleEpilog  appears NOWHERE in the WW layer at all
# None is a host import. An extraction that counts comment prose and locals
# inflates the one number a migration decision rests on, so the classes are
# DECLARED here with their reason and reported separately — never silently
# dropped (№31-C: an excluded row must say why it was excluded).
# ============================================================================
ARTIFACT_CLASSES = {
    "emplace_back": "std container member — plugin links its own STL",
    "push_back": "std container member — plugin links its own STL",
    "good": "comment prose match, not a call site",
    "msg": "comment prose match, not a call site",
    "field_0x0": "decomp field name in a comment, not a symbol",
    "sp54": "local variable (cXyz sp54, d_bg_s.cpp:769)",
    "ModuleProlog": "console REL prolog — dead on PC, comment-only",
    "ModuleEpilog": "console REL epilog — absent from the WW layer entirely",
    "path": "std::filesystem member / local — plugin-side",
    "max": "std::max — plugin links its own STL",
    "sin": "libm — plugin links its own CRT",
    "memset": "CRT — plugin links its own CRT",
    "getenv": "CRT — plugin links its own CRT",
}


def artifact_reason(name):
    """Why this name is NOT a host import, or None if it is a real one."""
    return ARTIFACT_CLASSES.get(name)


def collect_imports():
    """Host imports the WW layer makes, with their true site counts.

    site_count, never len(sites) -- the sites list is capped at 8 per subsystem
    and reading it as a population understated `info` as 51 against a real 382
    (§517)."""
    srcs = WC.load_build_sources() or []
    rows = [WC.classify_tu(s) for s in srcs]
    roster = WC.roster_union(rows)
    cres = C.run(roster)
    wres = W.run(roster, srcs, cres)
    idx = C.build_decl_index()

    subs = defaultdict(list)
    for r in roster:
        subs[C.group_of(r)].append(r)
    stem_owner, dir_owner = P._decl_owner_map(subs, srcs)

    imports = defaultdict(lambda: {"sites": 0, "subs": set()})
    for sub, v in wres.items():
        for name, d in (v.get("callbacks") or {}).items():
            decls = idx.get(name, [])
            if not decls:
                continue
            owners = {P._owner_of_decl(d, stem_owner, dir_owner) for d in decls}
            if None not in owners:
                continue        # WW-owned: not a host import at all (§517)
            e = imports[name]
            e["sites"] += d.get("site_count", 0)
            e["subs"].add(sub)
    return imports


DEFINE = r"^[ \t]*#[ \t]*define[ \t]+{}\b"
INLINE_BODY = r"^[^" + chr(10) + r"]*{}[ \t]*\([^;{{}}]*\)[^;{{}}]*{{"


_MACROS = None


def _macro_index():
    """Every `#define NAME` in the tree's headers, built once.

    The macro test USED to search only the paths the decl index lists for a
    name -- and for a macro those are USE sites, not the definition.
    `JUT_ASSERT` indexes to `d_bg_parts.h` etc. while the actual `#define` lives
    in `JUTAssert.h`, so three macros were misfiled as needing resolve(). That
    put 101 sites of pure compile-in into 19c's gate input as work that does not
    exist. Found by another lane reading the emitted manifest; the file was
    faithful and the TOOL was wrong."""
    global _MACROS
    if _MACROS is None:
        _MACROS = set()
        rx = re.compile(r"^[ \t]*#[ \t]*define[ \t]+([A-Za-z_]\w*)", re.M)
        for root in ("include", "libs", "src"):
            base = C.REPO / root
            if not base.is_dir():
                continue
            for h in list(base.rglob("*.h")) + list(base.rglob("*.hpp")):
                try:
                    _MACROS.update(rx.findall(
                        h.read_text(encoding="utf-8", errors="replace")))
                except OSError:
                    continue
    return _MACROS


def _decl_kind(name, idx):
    """macro | inline | None(needs a real symbol), from the DECLARATION."""
    if name in _macro_index():
        return "macro"
    for d in idx.get(name, [])[:4]:
        p = C.REPO / d
        if not p.is_file():
            continue
        txt = p.read_text(encoding="utf-8", errors="replace")
        if re.search(DEFINE.format(re.escape(name)), txt, re.M):
            return "macro"
        if re.search(INLINE_BODY.format(re.escape(name)), txt, re.M):
            return "inline"
    return None




def _resolve_against_image(names):
    """{name: 'resolved'|'missing'} against the built image's symbol table.

    GROUND TRUTH, not a heuristic: a name that is not in the shipped symbol
    table cannot be imported by a plugin, whatever it looked like in source.
    Returns {} when no image is available -- UNKNOWN, never 'clean' (№31-C).
    """
    img = C.REPO / "build/windows-msvc-relwithdebinfo/dusklight.exe"
    if not img.is_file():
        return {}
    try:
        import symbol_manifest as SM
        table = SM.load(str(img))
    except Exception:
        return {}
    if not table:
        return {}
    # COLLAPSED-DICT SWEEP (tale §967, applying §966's lesson): this verdict
    # came from `table`, whose keys are UNIQUE NAMES — so a name carried by
    # 685 raw entries read "resolved" with no hint that by-name binding cannot
    # pick one of them. Two defects in one line, both optimistic:
    #   · endswith("::" + n) is CLASS-BLIND (§957: getManager matched 10
    #     classes while the real import was JUTDbPrint::getManager)
    #   · exact hits ignore DUPLICATE COUNT (§960/§966's shape A)
    # A third verdict is added rather than widening "resolved", because
    # "ambiguous" is not a kind of resolved — the runtime returns MOD_CONFLICT.
    try:
        occ = SM.occurrences(str(img)) or {}
    except Exception:
        occ = {}
    out = {}
    for n in names:
        dup = occ.get(n, 0)
        if dup > 1:
            out[n] = "ambiguous"
            continue
        exact = n in table
        qualified = [k for k in table if k.endswith("::" + n)]
        if exact:
            out[n] = "resolved"
        elif len(qualified) == 1:
            out[n] = "resolved"
        elif len(qualified) > 1:
            out[n] = "ambiguous"
        else:
            out[n] = "missing"
    return out


def derivation_sha256():
    """Hash of what the (c) set is actually DERIVED from: the roster TUs.

    §535, found by evidence, not by review. The manifest recorded
    `count: 21` and verified FRESH -- tool_sha256 matched the generator and
    input_sha256 matched the .def -- while the live tool computed 15 at the same
    moment, in the same tree. Both stamps were valid and the content was stale,
    because NEITHER covers the source tree the (c) set is derived from. The tree
    had moved (crossing gates, HT-12, d_a_kb's banner, roster 72->73) and the
    answer moved with it.

    A freshness check that cannot detect the staleness it exists to detect is
    the "silence indistinguishable from a clean result" class this campaign
    keeps paying for. This closes it: cheap to VERIFY (hash the roster files),
    without re-running the expensive derivation.

    ADDED alongside the existing stamps, never replacing them -- they answer
    different questions and all three are worth having.
    """
    import hashlib
    try:
        srcs = WC.load_build_sources() or []
        roster = WC.roster_union([WC.classify_tu(s) for s in srcs])
    except Exception:
        return None
    h = hashlib.sha256()
    for rel in sorted(roster):
        f = C.REPO / rel
        h.update(rel.encode("utf-8"))
        h.update(hashlib.sha256(f.read_bytes()).digest() if f.is_file() else b"\0")
    return h.hexdigest()


def main():
    argv = sys.argv[1:]
    dpath = Path(argv[argv.index("--def") + 1]) if "--def" in argv else DEF
    # ====================================================================
    # --sdk: MEASURE AGAINST A DIFFERENT SDK TREE THAN THE ONE WE LIVE IN.
    #
    # Added 2026-08-18 (Foundry, Phase 2 re-measure). `--def` was already
    # parameterised; `SDK` was NOT, so a run in this tree ALWAYS counted
    # this tree's service headers. After the host fast-forwarded to
    # c880d46fb5 (epoch 2), the four new services -- Save/Stage/Item/
    # Window -- exist only in the `dusklight-main` clone. Running here
    # reported "102 published functions" and NAMED NONE OF THEM, which is
    # a confident answer to the PREVIOUS epoch's question.
    #
    # It could not error: an SDK path that resolves and parses cleanly is
    # indistinguishable from the RIGHT SDK path. Half a parameterised
    # input pair is the trap -- `--def` moving while `SDK` stayed pinned
    # is what let the two inputs describe different worlds silently.
    # ====================================================================
    global SDK
    if "--sdk" in argv:
        SDK = Path(argv[argv.index("--sdk") + 1])
        if not SDK.is_dir():
            print("--sdk path is not a directory: %s" % SDK)
            return 2
    # §536: hash the files ACTUALLY OPENED, rather than an input list somebody
    # remembered. Three stamps in a row each missed a different input; a fourth
    # enumeration would have the same shape. Tracing removes the judgment.
    import input_trace
    with input_trace.trace() as _opened:
        exports = exported_identifiers(dpath)
        svc = sdk_service_symbols()
        imports = collect_imports()
        idx = C.build_decl_index()
    inputs_sha = input_trace.digest(_opened)
    inputs_n = len(_opened)

    print("STEP 15 — WW PLUGIN BINDING PLAN")
    # `--def` exists to point at ANOTHER checkout's build (the whole purpose is
    # comparing against stock upstream), so never assume it sits under our repo.
    try:
        shown = dpath.relative_to(C.REPO)
    except ValueError:
        shown = dpath
    print(f"  export surface : {shown}")
    if exports is None:
        print("  VERDICT: UNKNOWN — no export surface at that path. Nothing is "
              "classified; a missing oracle is not a clean result (№31-C).")
        return 2
    print(f"                   {len(exports)} distinct exported identifiers")
    print(f"  SDK services   : {len(svc)} published functions")
    print(f"  host imports   : {len(imports)} symbols, "
          f"{sum(e['sites'] for e in imports.values())} sites\n")

    # SDK record kinds (sdk/include/mods/api.h ModMetaKind). Emitted rather than
    # a Foundry vocabulary: the SDK already enumerates this, and inventing a
    # parallel schema is how two rosters start drifting (HT-15).
    #
    # ONE CORRECTION to the advisory's list, offered tentatively: it named
    # ModMetaExport for the service bucket. Export (kind 3) is what a mod
    # PROVIDES to other mods; what a mod CONSUMES from the host is
    # ModMetaImport (kind 2) -- and kind 2 is the one carrying
    # major_version/min_minor_version, i.e. the negotiation the advisory is
    # relying on. If that reading is wrong the versioning argument moves with it.
    RECORD = {
        "(a) SERVICE — published SDK, versioned":
            ("MOD_META_IMPORT (2)", "SDK negotiates major/min_minor at load"),
        "(b) LINK — in the export surface, direct call":
            ("none — import library",
             "the OS dynamic linker refuses the DLL at load"),
        "(c) NEEDS resolve() — not exported, not inline":
            ("MOD_META_HOOK_NAME (6) when hooking; NONE when calling",
             "19c gate — see the gap note below"),
        "(e) HEADER-INLINE/TEMPLATE — compiles into the caller":
            ("none", "nothing to gate — no symbol exists"),
        "(e) HEADER-MACRO — compiles into the caller":
            ("none", "nothing to gate — no symbol exists"),
    }

    buckets = defaultdict(lambda: {"n": 0, "sites": 0, "ex": []})
    for name, e in imports.items():
        if name in svc:
            k = "(a) SERVICE — published SDK, versioned"
        elif name in exports:
            k = "(b) LINK — in the export surface, direct call"
        else:
            # Not exported is NOT the same as not reachable. A macro or an
            # inline/template body compiles INTO the caller: a plugin that
            # includes the same header gets it with no symbol at all. Counting
            # those as debt inflated the "long pole" from ~29 to 772.
            k = {"macro": "(e) HEADER-MACRO — compiles into the caller",
                 "inline": "(e) HEADER-INLINE/TEMPLATE — compiles into the caller"
                 }.get(_decl_kind(name, idx),
                       "(c) NEEDS resolve() — not exported, not inline")
        b = buckets[k]
        b["n"] += 1
        b["sites"] += e["sites"]
        b["ex"].append((e["sites"], name))

    for k in sorted(buckets):
        b = buckets[k]
        rec, gate = RECORD.get(k, ("?", "?"))
        print(f"  {k}")
        print(f"      SDK record: {rec}")
        print(f"      load gate : {gate}")
        print(f"      {b['n']:5d} symbols   {b['sites']:6d} sites")
    print()

    unres = buckets.get("(c) NEEDS resolve() — not exported, not inline")
    if unres:
        print("  THE (c) SET — every host import needing resolve(). Ranked by "
              "sites. Some are CRT/STL names declared outside the indexed tree "
              "(push_back, memset, getenv) rather than TP functions:")
        for n, name in sorted(unres["ex"], reverse=True)[:20]:
            print(f"      {n:5d} sites  {name}")
        if len(unres["ex"]) > 20:
            print(f"      … {len(unres['ex']) - 20} more")

    if "--emit" in argv:
        # HousingTemp's C7: asserting the gate's input is non-empty is not
        # enough -- one stray hook record satisfies that. The gate must assert
        # its count EQUALS the import list, and that needs the list to be a
        # readable artifact. It was not one; this makes it one.
        out = C.REPO / "docs/WW Linked/ww-import-manifest.txt"
        rows = sorted(unres["ex"], reverse=True) if unres else []
        with out.open("w", encoding="utf-8") as f:
            f.write("# WW plugin import manifest — the (c) set: host imports\n")
            f.write("# reachable by NEITHER a published SDK service NOR the\n")
            f.write("# export surface, so each needs resolve() at load.\n")
            # Provenance, adopting ww_layer_manifest.py's post-§491 pattern.
            # This file was READ as evidence of a design flaw while the real
            # defect was in the generator -- so a consumer must be able to tell
            # a stale manifest from a current one WITHOUT rerunning the tool.
            # A gate should refuse a manifest older than its generator.
            import hashlib
            tool = Path(__file__).read_bytes()
            defb = dpath.read_bytes() if dpath.is_file() else b""
            f.write("# Generated by tools/foundry/binding_plan.py --emit\n")
            f.write(f"# regenerate: python tools/foundry/binding_plan.py --emit\n")
            f.write(f"# tool_sha256:  {hashlib.sha256(tool).hexdigest()}\n")
            f.write(f"# input_sha256: {hashlib.sha256(defb).hexdigest()}\n")
            # §536: TRACED, not enumerated. Supersedes the judgment-based
            # stamps above -- it covers SDK headers and the decl index, which
            # derivation_sha256 provably did not.
            f.write(f"# inputs_sha256: {inputs_sha}" + chr(10))
            f.write(f"# inputs_count: {inputs_n}   "
                    f"(files this run actually opened)" + chr(10))
            _d = derivation_sha256()
            f.write(f"# derivation_sha256: {_d or 'UNKNOWN'}   "
                    f"(roster TU contents -- the input the count actually depends on)\n")
            f.write(f"# export surface: {shown}\n")
            # §535 MANIFEST HYGIENE (Housing; conflict declared -- Housing also
            # RECOMMENDED this in §534, so it needs an independent audit).
            #
            # 7 of the 21 entries do not exist in the built image, and two of
            # them -- `field_0x0`, `sp54` -- are not functions at all. Root cause
            # is the MOST VEXING PARSE: `cXyz sp54(player->current.pos);` is
            # syntactically identical to a declaration `cXyz sp54(params);`, so
            # census_axis_c.DECL indexes it as a function, it then reads
            # call-shaped, and it lands in the (c) set. A regex cannot resolve
            # that ambiguity without type knowledge.
            #
            # DELIBERATELY NOT FIXED AT THE REGEX. DECL is shared by Axis
            # C/W/D/P and every adopted verdict depends on it; changing it would
            # move V1-V10 and demand a full re-derivation plus P1 re-audit. That
            # is a Foundry decision with a stated blast radius, not a side effect
            # of a manifest fix.
            #
            # So the artifact is annotated with GROUND TRUTH instead of a
            # heuristic: does the symbol exist in the built image? Entries are
            # KEPT, never dropped -- a name that fails to resolve is exactly what
            # 19b's MISSING category is for, and deleting it would hide the
            # finding rather than record it.
            resolved = _resolve_against_image([nm for _c, nm in rows])
            n_ok = sum(1 for v in resolved.values() if v == "resolved")
            n_missing = sum(1 for v in resolved.values() if v == "missing")
            f.write(f"# count: {len(rows)}\n")
            if resolved:
                f.write(f"# resolved: {n_ok}\n")
                f.write(f"# missing: {n_missing}   "
                        f"(present in the list, absent from the image -- 19b MISSING)\n")
            else:
                f.write("# resolved: UNKNOWN (no built image to check against)\n")
            f.write("# columns: name<TAB>sites<TAB>image\n")
            for n, name in rows:
                f.write(f"{name}\t{n}\t{resolved.get(name, 'unknown')}\n")
        print(f"\n  EMITTED {out.relative_to(C.REPO)} — {len(rows)} entries. "
              f"This is 19c's input list; the gate asserts its own count "
              f"equals this one (C7).")

    print("\n  GAP FOR 19c — the record kinds are HOOK-oriented, and these 10 are")
    print("  CALLS, not hooks. We want to invoke cM_ssin, not intercept it.")
    print("  MOD_META_HOOK_NAME covers resolve-then-hook; there is no record for")
    print("  resolve-then-CALL, so a load-time gate built only from hook records")
    print("  would validate none of them. The gate's input must be the import")
    print("  list itself, not the mod's hook records.")

    print("\n  LIMITS. Identifier-level matching: overloads collapse to one name, "
          "so this answers 'can a plugin reach this NAME', not 'which overload'. "
          "The (c/d) bucket is NOT proven unreachable — the embedded symbol "
          "manifest that resolve() reads lives in the linked image and cannot be "
          "consulted from source. Splitting c from d needs a built binary.")
    return 0


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    raise SystemExit(main())
