#!/usr/bin/env python3
# ============================================================================
# port_kit.py — K1/K2 of the port-automation plan (tale §849, user go 08-13).
#
# The MATCHED-port pipeline is ~70% mechanical; this kit does the mechanical
# parts and NOTHING semantic — History remains reviewer and owner of demo
# bindings, event plumbing, and DN-10 step-1 reading.
#
#   K1  header <Arc> [--jnt <member.bdl>] [--write]
#       dRes_INDEX/dRes_ID enums generated from the DISC arc's own RARC node
#       + file-entry tables (the donor's index space verbatim; closes every
#       [res-header] name-gap row). --jnt adds the joint enum from the BDL's
#       JNT1 name table. Default prints; --write lands
#       assets/GZ2E01/res/Object/<Arc>.h for a BUILD-QUEUE row.
#   K1-GATE  --golden Jb
#       Regenerates Jb's enums from the disc and diffs them against History's
#       HAND-AUTHORED assets Jb.h (§822) — the kit ships only equal.
#   K2  scaffold <ActorStem> <ObjName> <ProfName>
#       Prints the §747 registration blocks (fpcNm enum row, register row,
#       OBJNAME route, files.cmake, roster note) with live-grepped anchors +
#       next-free values. TEXT ONLY — the lane applies, the gate builds.
#
# Read-only by default; --write is the single write path and it is a
# GENERATED RECEIVER HEADER (not donor-format bytes — kit_output_law governs
# donor-format writes; this is receiver code generation, banner-attributed).
# ============================================================================
import re
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(HERE))
import ww_disc as wd


def be16(b, o):
    return struct.unpack_from(">H", b, o)[0]


def be32(b, o):
    return struct.unpack_from(">I", b, o)[0]


def default_iso():
    import json
    import os
    pth = os.environ.get("WW_ISO", "")
    if not pth:
        try:
            cfg = os.path.expandvars(r"%APPDATA%\TwilitRealm\Dusklight\config.json")
            pth = json.load(open(cfg, encoding="utf-8")).get("backend.extraIsoPath", "")
        except OSError:
            pth = ""
    return pth or None


def rarc_nodes(a):
    """[(nodeType, [(entryIndex, fileId, name)])] — node-aware walk; the
    global file-entry index IS the donor's dRes_INDEX space."""
    if a[:4] == b"Yaz0":
        a = wd.yaz0_decompress(a)
    if a[:4] != b"RARC":
        raise ValueError("not RARC")
    info = 0x20
    n_nodes = be32(a, info + 0)
    node_off = info + be32(a, info + 4)
    ent_off = info + be32(a, info + 0xC)
    strs = info + be32(a, info + 0x14)

    def cstr(off):
        end = a.index(b"\0", strs + off)
        return a[strs + off:end].decode("ascii", "replace")

    out = []
    for i in range(n_nodes):
        nb = node_off + i * 0x10
        ntype = a[nb:nb + 4].decode("ascii", "replace")
        n_files = be16(a, nb + 0xA)
        first = be32(a, nb + 0xC)
        entries = []
        for j in range(first, first + n_files):
            e = ent_off + j * 0x14
            attr = be16(a, e + 4)
            if attr & 0x1100 != 0x1100:      # files only (skip dirs . ..)
                continue
            fid = be16(a, e + 0)
            name = cstr(be16(a, e + 6))
            entries.append((j, fid, name))
        out.append((ntype, entries))
    return out


def jnt_names(bdl):
    """Joint names from a J3D model's JNT1 string table."""
    if bdl[:4] != b"J3D2":
        return []
    seccnt = be32(bdl, 12)
    off = 0x20
    for _ in range(seccnt):
        tag = bdl[off:off + 4]
        size = be32(bdl, off + 4)
        if tag == b"JNT1":
            tab = off + be32(bdl, off + 0x14)
            cnt = be16(bdl, tab)
            return [(bdl[tab + be16(bdl, tab + 4 + i * 4 + 2):
                         bdl.index(b"\0", tab + be16(bdl, tab + 4 + i * 4 + 2))]
                     ).decode("ascii", "replace") for i in range(cnt)]
        off += size
    return []


def enum_stem(name):
    return re.sub(r"[^A-Za-z0-9]", "_", name.rsplit(".", 1)[0]).upper()


def type3(node):
    t = node.strip()
    return t[:3] if len(t) > 3 else t


def gen_header(arc_name, jnt_member=None):
    iso = default_iso()
    if not iso:
        print("no ISO configured (backend.extraIsoPath / WW_ISO)")
        return None
    f, boot = wd.iso_open(iso, wd.WW_IDS)
    raw = wd.iso_read_file(f, boot, "res/Object/%s.arc" % arc_name)
    nodes = rarc_nodes(raw)
    up = arc_name.upper()
    L = ["#ifndef RES_%s_H" % up, "#define RES_%s_H" % up, "",
         "//",
         "// Generated by port_kit.py (K1, tale §850) from archive: %s.arc" % arc_name,
         "// off the donor disc — the donor's own RARC index space, verbatim.",
         "// Do not manually modify this file or your changes will be overwritten.",
         "//", "",
         "enum dRes_INDEX_%s {" % up]
    body_idx, body_id = [], []
    for ntype, entries in nodes:
        if ntype == "ROOT" or not entries:
            continue
        body_idx.append("    /* %s */" % ntype)
        body_id.append("    /* %s */" % ntype)
        for j, fid, name in entries:
            stem = "%s_%s_%s" % (up, type3(ntype), enum_stem(name))
            body_idx.append("    dRes_INDEX_%s_e=0x%X," % (stem, j))
            body_id.append("    dRes_ID_%s_e=0x%X," % (stem, fid))
    L += body_idx + ["};", "", "enum dRes_ID_%s {" % up] + body_id + ["};"]
    if jnt_member:
        for _t, entries in nodes:
            for _j, _fid, name in entries:
                if name.lower() == jnt_member.lower():
                    data = None
                    for nm, d in wd.rarc_list(raw):
                        if nm.lower() == jnt_member.lower():
                            data = wd.yaz0_decompress(d) if d[:4] == b"Yaz0" else d
                    if data:
                        js = jnt_names(data)
                        if js:
                            L += ["", "enum %s_JNT {" % up]
                            L += ["    %s_JNT_%s_e=0x%X," % (up, enum_stem(n), i)
                                  for i, n in enumerate(js)]
                            L += ["};"]
    L += ["", "#endif /* RES_%s_H */" % up, ""]
    return "\n".join(L)


def golden(arc_name):
    """K1 gate: regenerate vs History's hand-authored header — enums only."""
    gen = gen_header(arc_name)
    ref_p = REPO / "assets" / "GZ2E01" / "res" / "Object" / (arc_name + ".h")
    if gen is None or not ref_p.is_file():
        print("GOLDEN: cannot run (missing generation or reference)")
        return 2
    def enum_lines(text):
        return [ln.strip() for ln in text.splitlines()
                if re.match(r"\s*dRes_(INDEX|ID)_\w+_e=0x[0-9A-Fa-f]+,", ln)]
    g, r = enum_lines(gen), enum_lines(ref_p.read_text(encoding="utf-8"))
    if g == r:
        print("GOLDEN %s: EQUAL — %d enum rows match History's hand header exactly"
              % (arc_name, len(g)))
        return 0
    print("GOLDEN %s: DIVERGES — gen %d rows vs ref %d rows" % (arc_name, len(g), len(r)))
    for a, b in zip(g, r):
        if a != b:
            print("  gen: %s\n  ref: %s" % (a, b))
            break
    only_g = set(g) - set(r)
    only_r = set(r) - set(g)
    for x in sorted(only_g)[:5]:
        print("  gen-only: %s" % x)
    for x in sorted(only_r)[:5]:
        print("  ref-only: %s" % x)
    return 1


def scaffold(stem, objname, profname):
    """K2: the §747 registration blocks with live-grepped anchors."""
    # Calibrated to the REAL table shape (X-macro rows with /* 0xNNN */
    # comments, f_pc_name.h:831-835 band) — the first-run regex guessed a
    # `= 0x` form that does not exist and reported 0x330/0 rows.
    fpc = (REPO / "include" / "f_pc" / "f_pc_name.h").read_text(encoding="utf-8", errors="replace")
    ww_rows = re.findall(r"/\*\s*(0x[0-9A-Fa-f]+)\s*\*/\s*X\(fpcNm_\w+_e\)", fpc)
    used = sorted(int(v, 16) for v in ww_rows)
    nxt = (used[-1] + 1) if used else -1
    reg = (REPO / "src" / "d" / "ext_plugin" / "ww_profile_register.cpp")
    reg_rows = len(re.findall(r"^\s*\{\s*.*fpcNm_\w+_e",
                              reg.read_text(encoding="utf-8", errors="replace"),
                              re.M)) if reg.is_file() else -1
    print("=" * 70)
    print("K2 SCAFFOLD — %s (OBJNAME '%s', profile %s)" % (stem, objname, profname))
    print("TEXT ONLY: apply by hand, queue the row, the gate builds. (§747 x5 precedent)")
    print("=" * 70)
    print("""
1. include/f_pc/f_pc_name.h — enum row (next free in the WW band):
     fpcNm_%(P)s_e = 0x%(N)X,

2. src/d/ext_plugin/ww_profile_register.cpp — register row (currently %(R)s rows;
   grow the static_assert WITH REASON, §747):
     { fpcNm_%(P)s_e, &g_profile_%(S)s },

3. src/d/d_stage.cpp — data-keyed OBJNAME route (verify '%(O)s' absent
   receiver-side FIRST — the Jb1 precedent check):
     OBJNAME route: "%(O)s" -> fpcNm_%(P)s_e

4. files.cmake — source registration:
     src/d/actor/d_a_%(s)s.cpp

5. Donor-disc roster (mods-src/ww_donor_disc/main.cpp): add "%(A)s" if the
   actor resolves an arc not yet served; kTpCollisionAlias if the name
   collides TP-side (§716 mechanism).

6. Header: port_kit.py header %(A)s --write  (K1; closes the [res-header] rows)

7. Preflight card: port_preflight.py d_a_%(s)s --post src/d/actor/d_a_%(s)s.cpp
""" % {"P": profname, "N": nxt, "R": reg_rows, "S": stem, "s": stem,
       "O": objname, "A": stem.split("_")[-1].capitalize()})
    return 0


def main():
    if len(sys.argv) < 2:
        print("usage: port_kit.py header <Arc> [--jnt <member.bdl>] [--write] | "
              "--golden <Arc> | scaffold <stem> <ObjName> <ProfName>")
        return 2
    if sys.argv[1] == "--golden":
        return golden(sys.argv[2])
    if sys.argv[1] == "header":
        arc = sys.argv[2]
        jnt = sys.argv[sys.argv.index("--jnt") + 1] if "--jnt" in sys.argv else None
        text = gen_header(arc, jnt)
        if text is None:
            return 2
        if "--write" in sys.argv:
            out = REPO / "assets" / "GZ2E01" / "res" / "Object" / (arc + ".h")
            out.write_text(text, encoding="utf-8", newline="\n")
            print("wrote %s — queue it with its port row" % out)
        else:
            print(text)
        return 0
    if sys.argv[1] == "scaffold" and len(sys.argv) >= 5:
        return scaffold(sys.argv[2], sys.argv[3], sys.argv[4])
    print("bad args")
    return 2


if __name__ == "__main__":
    sys.exit(main())
