#!/usr/bin/env python3
"""Generate include/d/d_demo_leftover_catalog.inc from all unique Demo*.arc BMDs."""
from __future__ import annotations

import importlib.util
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "include" / "d" / "d_demo_leftover_catalog.inc"
OBJ = Path(r"D:/XXXXXXX/Ex TP/files/res/Object")

sys.path.insert(0, str(ROOT / "tools" / "companion_mod"))
from extract_rarc import parse_rarc  # noqa: E402

spec = importlib.util.spec_from_file_location(
    "scan", Path(__file__).resolve().parent / "scan_demo_leftovers.py"
)
scan = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(scan)

# Must match dDemoLeftoverViewer::Category
CAT_GOLD = 0
CAT_LINK = 1
CAT_MIDNA = 2
CAT_WOLF = 3
CAT_NPC = 4
CAT_BOSS = 5
CAT_PROP = 6


def classify(name: str) -> tuple[int, str]:
    low = name.lower()
    # kind
    if "henkeiface" in low or "hiface" in low or ("_fc_" in low and "face" not in low):
        kind = "face"
    elif "henkei" in low and "wl" in low:
        kind = "piece"
    elif "_hd_" in low or "hihead" in low or "_hd_tmp" in low:
        kind = "head"
    elif "_hl_" in low or "_hr_" in low or "hand" in low or "hairhand" in low:
        kind = "hand"
    elif "tongue" in low or "mask" in low or "blend" in low:
        kind = "piece"
    elif "original" in low or "high" in low or "_bd_" in low or "_gp_" in low:
        kind = "body"
    else:
        kind = "mesh"

    # leftover gold markers
    gold = any(
        x in low
        for x in (
            "original",
            "_high_",
            "henkei",
            "hiface",
            "demo00_",
            "ctz1",
            "wb_cut00_gp_original",
        )
    )

    if gold and ("link" in low or "wb_" in low or "ctz" in low or "kusari" in low or "wl_" in low):
        cat = CAT_GOLD
    elif "midna" in low or "mdhair" in low or "mdmask" in low or "_md_" in low:
        cat = CAT_MIDNA
    elif "wl_" in low or "wolf" in low:
        cat = CAT_WOLF
    elif "link" in low or "alink" in low:
        cat = CAT_LINK
    elif any(
        x in low
        for x in (
            "zant",
            "zelda",
            "zelr",
            "ganon",
            "gnd",
            "b_g",
        )
    ):
        cat = CAT_BOSS
    elif any(
        x in low
        for x in (
            "moi",
            "yelia",
            "kolin",
            "uri",
            "aru",
            "bou",
            "cow",
            "fwood",
            "grein",
            "msaya",
            "manb",
            "manc",
            "masa",
            "mata",
            "mbna",
            "mcna",
            "mona",
            "wada",
            "wanb",
            "wcna",
            "wgna",
            "wona",
            "yami",
            "s2_",
            "rd2",
            "rbbb",
            "rdwb",
            "wbrd",
        )
    ):
        cat = CAT_NPC
    else:
        cat = CAT_PROP

    # Prefer gold for true leftover tokens even if also link/midna
    if any(x in low for x in ("original", "henkeiface", "hiface", "demo00_")):
        if "midna" in low:
            cat = CAT_GOLD if "tmp" in low else CAT_MIDNA
        elif "link" in low or "wb_" in low or "ctz" in low or "wl_" in low:
            cat = CAT_GOLD

    return cat, kind


def short_label(arc: str, name: str, kind: str) -> str:
    base = name
    if base.lower().endswith(".bmd"):
        base = base[:-4]
    # strip demoXX_ prefix noise lightly
    return f"[{kind}] {arc}/{base}"


def main() -> int:
    by_sha: dict[str, tuple[str, str, int]] = {}
    for arc_path in sorted(OBJ.glob("Demo*.arc")):
        raw = arc_path.read_bytes()
        rarc = scan.ensure_rarc(raw)
        for _fid, name, _off, size, payload in parse_rarc(rarc):
            low = name.lower()
            if not (low.endswith(".bmd") or low.endswith(".bdl")):
                continue
            h = scan.sha16(payload)
            if h not in by_sha:
                by_sha[h] = (arc_path.stem, name, size)

    rows = []
    for h, (arc, name, size) in sorted(by_sha.items(), key=lambda kv: (kv[1][0], kv[1][1])):
        cat, kind = classify(name)
        label = short_label(arc, name, kind)
        rows.append((cat, kind, label, arc, name, size))

    rows.sort(key=lambda r: (r[0], r[3], r[4]))

    lines = [
        "// AUTO-GENERATED by tools/demo_cut_content/gen_demo_catalog.py — do not edit.",
        f"// Unique Demo BMD/BDL count: {len(rows)}",
        "static const Entry kCatalog[] = {",
    ]
    for cat, kind, label, arc, name, size in rows:
        # Escape quotes in names (none expected)
        lines.append(
            f'    {{{cat}, "{kind}", "{label}", "{arc}", "{name}"}},  // {size} B'
        )
    lines.append("};")
    lines.append(f"static constexpr int kCatalogCount = {len(rows)};")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(rows)} entries)")

    hist: dict[int, int] = defaultdict(int)
    for cat, *_ in rows:
        hist[cat] += 1
    names = ["GOLD", "LINK", "MIDNA", "WOLF", "NPC", "BOSS", "PROP"]
    for i, n in enumerate(names):
        print(f"  {n}: {hist[i]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
