// KIT-LINEAGE: native-port
// KIT-DONOR: d/actor/d_a_spc_item01.cpp
// KIT-DONOR-REF: zeldaret/tww@1d57f0468986987ec26a3d1800bdc1aaad3794db
// KIT-DONOR-STATUS: MatchingFor
//
// Generated by dtk
// Translation Unit: d_a_spc_item01.cpp
//
// ============================================================================
// §327 WW WALL SHIELD / SPECIAL PLACED ITEM (SPC_ITEM01) DIRECT PORT — body
// VERBATIM from the WW donor (D:/XXXXXXX/WW DP/src/d/actor/d_a_spc_item01.cpp).
// This is the quest object on Grandma's wall (Hero's Shield, WW itemNo 0x3B).
//
// Port adaptations (each banner-marked inline; toripost §253 / ba1 §261 recipes):
//   · base-class member renames: mPhs->mPhase, mStts->mCcStts, mCyl->mCcCyl
//     (the port's native TP daItemBase_c — same lineage, TP names);
//   · WW dItem_data lookups (getFieldArc/getHeapSize/item_info/effect_info) ride
//     a LOCAL VALUE-FAITHFUL WW SUBSET table — the port's dItem_data is
//     TP-NUMBERED and this actor's m_itemNo carries WW DZR numbering.
//     >>> NAMED DEBT (do-not-improvise): full WW dItem_data port. The subset
//         covers the SHIELD row (0x3B) only — the one SPitem quest placement in
//         the Outset restoration. Rupee / JOY_PENDANT (0x1F) / KNIGHTS_CREST
//         (0x48) SPitem placements need the WW "Always" field-bundle rows (BDL +
//         BCK/BTK anims) and fail create cleanly with a log until the full WW
//         item-data port lands. NO stand-in visuals are improvised. <<<
//   · WW dItemNo_* names RENAMED WWITEM_* (the port's TP enum owns
//     dItemNo_SHIELD_e etc. at DIFFERENT values — a #define would corrupt it);
//   · dComIfGs_isEventBit(WW 0x0E20) routes to the DONOR event-flag block via
//     d_ext_save_flags_route.h (LAST include, §303 rule) — Grandma's ba1 port
//     WRITES that flag through the same route, so the shield sees her gift;
//   · #1 DN-3: model via dExtNpcMount_acquireModelData("Vshin", "vshin.bdl")
//     in a local heap CB (the port's CheckFieldItemCreateHeap indexes TP tables;
//     the WW SHIELD field row is model-only — anm indices all -1 — so the CB is
//     the donor path exactly);
//   · isRupee() is the VERBATIM WW free function (d_item.cpp:2800), local —
//     the port has no WW-numbered rupee query;
//   · cPhs_State -> cPhs_Step; setSimple/mAcch.Set port arity; animPlay WW
//     5-arg (brk1,brk2,btk1,btk2,bck) -> port 6-arg order remap.
// ============================================================================

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/actor/d_a_spc_item01.h"
#include "d/d_bg_s_acch.h"
#include "d/d_com_inf_game.h"
#include "f_op/f_op_actor_mng.h"
#include "m_Do/m_Do_mtx.h"
#include "m_Do/m_Do_ext.h"                // §327 mDoExt_J3DModel__create
#include "SSystem/SComponent/c_lib.h"     // §327 cLib_checkBit / cLib_chaseF / cLib_chaseAngleS
#include "d/d_ext_npc_mount.h"            // §327 DN-3 parse-at-consume model resolver
#include "d/d_ext_ww_actor_shims.h"       // §327 WWEV_UNK_0E20 / TEV_TYPE_ACTOR / fopAcStts_* / cCcD_* / AT_TYPE_ALL
#include "dusk/logging.h"                 // §327 uncovered-row named-debt log
// §327 SYMBOL ROUTE — MUST BE THE LAST INCLUDE (§303 rule). Routes the verbatim
// dComIfGs_isEventBit(WW 0x0E20) read to the donor event-flag block, where the
// ba1 (Grandma) port writes it. TP TUs never include this.
#include "d/d_ext_save_flags_route.h"
#include "d/d_kankyo_ww.h"           // §404 WW lighting write-path (was the empty stub)

// §327 ========================================================================
// WW dItemNo values (WW d_item_data.h) — RENAMED WWITEM_* because the port's TP
// enum owns dItemNo_SHIELD_e / _JOY_PENDANT_e / rupee names at DIFFERENT values.
#define WWITEM_GREEN_RUPEE_e   0x01
#define WWITEM_BLUE_RUPEE_e    0x02
#define WWITEM_YELLOW_RUPEE_e  0x03
#define WWITEM_RED_RUPEE_e     0x04
#define WWITEM_PURPLE_RUPEE_e  0x05
#define WWITEM_ORANGE_RUPEE_e  0x06
#define WWITEM_SILVER_RUPEE_e  0x0F
#define WWITEM_JOY_PENDANT_e   0x1F
#define WWITEM_SHIELD_e        0x3B
#define WWITEM_KNIGHTS_CREST_e 0x48
// §406: TEV_TYPE_* centralized in d/d_kankyo_ww.h (donor values verbatim).
// Donor draw-prio slot absent -> port ground/ambient slot (pig/toripost precedent).
#define fpcDwPi_SPC_ITEM01_e fpcDwPi_E_RD_e

// ----------------------------------------------------------------------------
// §327 WW dItem_data SUBSET — value-faithful rows from the WW donor
// d_item_data.cpp for the item numbers this actor can present natively today.
//   0x3B SHIELD: field_item_res[0x3B] = { arc "Vshin",
//     bmd dRes_INDEX_VSHIN_BDL_VSHIN_e (res id 3 == "vshin.bdl", RARC-parsed
//     from D:/XXXXXXX/Ex WW/files/res/Object/Vshin.arc), anms all -1,
//     J3D flags 0x11000022, heap 0x5000 };  item_resource[0x3B].mHeapSize ==
//     0x5000 (the donor _create uses getHeapSize, the ITEM row — same value);
//     item_info[0x3B] = { shadow 0x28, H 0x3C, R 0x28, flag 0x10 };
//     effect_info[0x3B] = { ID_SCENE_END, ID_SCENE_END } (no appear effect).
// ----------------------------------------------------------------------------
struct dExtSpc_wwRow_t {
    u8 itemNo;
    const char* fieldArc;    // WW field_item_res mArc
    const char* bmdMember;   // WW field bmd res id -> member name (RARC-parsed)
    u32 heapSize;            // WW dItem_data::getHeapSize (item_resource row)
    u32 j3dFlags;            // WW field row mUnknown
    u8 shadowSize;           // WW item_info
    u8 h;                    // WW item_info (getHeight)
    u8 r;                    // WW item_info (getR)
    u8 flag;                 // WW item_info (chkFlag mask source)
    u16 appearEffect;        // WW effect_info m_appear; 0xFFFF == ID_SCENE_END (none)
};
static const dExtSpc_wwRow_t l_wwRows[] = {
    { WWITEM_SHIELD_e, "Vshin", "vshin.bdl", 0x5000, 0x11000022, 0x28, 0x3C, 0x28, 0x10, 0xFFFF },
};

static const dExtSpc_wwRow_t* dExtSpc_wwRow(u8 itemNo) {
    for (u32 i = 0; i < ARRAY_SIZE(l_wwRows); i++) {
        if (l_wwRows[i].itemNo == itemNo) {
            return &l_wwRows[i];
        }
    }
    return NULL;
}

// §327 WW dItem_data::checkAppearEffect / getAppearEffect over the subset.
static bool dExtSpc_wwCheckAppearEffect(u8 itemNo) {
    const dExtSpc_wwRow_t* row = dExtSpc_wwRow(itemNo);
    return row != NULL && row->appearEffect != 0xFFFF;
}
static u16 dExtSpc_wwGetAppearEffect(u8 itemNo) {
    const dExtSpc_wwRow_t* row = dExtSpc_wwRow(itemNo);
    return row != NULL ? row->appearEffect : 0;
}

// §327 isRupee — VERBATIM WW free function (D:/XXXXXXX/WW DP/src/d/d_item.cpp:2800),
// constants renamed WWITEM_* (see above). Local: the port has no WW-numbered query.
static BOOL isRupee(u8 itemNo) {
    BOOL isRupee = FALSE;
    if (itemNo == WWITEM_GREEN_RUPEE_e || itemNo == WWITEM_BLUE_RUPEE_e || itemNo == WWITEM_YELLOW_RUPEE_e || itemNo == WWITEM_RED_RUPEE_e ||
        itemNo == WWITEM_PURPLE_RUPEE_e || itemNo == WWITEM_ORANGE_RUPEE_e || itemNo == WWITEM_SILVER_RUPEE_e)
    {
        isRupee = TRUE;
    }
    return isRupee;
}
// §327 ========================================================================

namespace daSpcItem01_prm {
    inline u8 getItemNo(daSpcItem01_c* i_this) { return fopAcM_GetParam(i_this) >> 0 & 0xFF; }
    inline u16 getFlag(daSpcItem01_c* i_this) { return fopAcM_GetParam(i_this) >> 8 & 0xFFFF; }
};

const float magic_double = -24.0f;

static dCcD_SrcCyl l_cyl_src = {
    // dCcD_SrcGObjInf
    {
        /* Flags             */ 0,
        /* SrcObjAt  Type    */ 0,
        /* SrcObjAt  Atp     */ 0,
        /* SrcObjAt  SPrm    */ 0,
        /* SrcObjTg  Type    */ AT_TYPE_ALL,
        /* SrcObjTg  SPrm    */ cCcD_TgSPrm_Set_e | cCcD_TgSPrm_IsEnemy_e,
        /* SrcObjCo  SPrm    */ cCcD_CoSPrm_Set_e | cCcD_CoSPrm_IsOther_e | cCcD_CoSPrm_VsEnemy_e,
        /* SrcGObjAt Se      */ 0,
        /* SrcGObjAt HitMark */ 0,
        /* SrcGObjAt Spl     */ 0,
        /* SrcGObjAt Mtrl    */ 0,
        /* SrcGObjAt SPrm    */ 0,
        /* SrcGObjTg Se      */ 0,
        /* SrcGObjTg HitMark */ 0,
        /* SrcGObjTg Spl     */ 0,
        /* SrcGObjTg Mtrl    */ 0,
        /* SrcGObjTg SPrm    */ 4,
        /* SrcGObjCo SPrm    */ 0,
    },
    // cM3dGCylS
    {{
        /* Center */ {0.0f, 0.0f, 0.0f},
        /* Radius */ 0.0f,
        /* Height */ 0.0f,
    }},
};

// §327 WW-numbered per-item getters — the port base's virtuals index the TP
// dItem_data tables with m_itemNo, which is WW-numbered here. Values ride the
// local WW subset row; a missing row returns the WW-neutral defaults the base
// paths treat as inert (0 shadow/H/R, no flags, no fixed anm frames).
BOOL daSpcItem01_c::chkFlag(int flag) {
    const dExtSpc_wwRow_t* row = dExtSpc_wwRow(m_itemNo);
    return row != NULL ? (row->flag & flag) : 0;
}
s8 daSpcItem01_c::getTevFrm() { return -1; }   // §327 WW SHIELD row mTevFrm == -1
s8 daSpcItem01_c::getBtpFrm() { return -1; }   // §327 WW rows carry no btp frame
u8 daSpcItem01_c::getShadowSize() {
    const dExtSpc_wwRow_t* row = dExtSpc_wwRow(m_itemNo);
    return row != NULL ? row->shadowSize : 0;
}
u8 daSpcItem01_c::getCollisionH() {
    const dExtSpc_wwRow_t* row = dExtSpc_wwRow(m_itemNo);
    return row != NULL ? row->h : 0;
}
u8 daSpcItem01_c::getCollisionR() {
    const dExtSpc_wwRow_t* row = dExtSpc_wwRow(m_itemNo);
    return row != NULL ? row->r : 0;
}

// §327 local heap CB — replaces CheckFieldItemCreateHeap (TP-table-indexed).
// The covered WW field rows are MODEL-ONLY (anm indices all -1), so building
// just mpModel through the DN-3 resolver IS the donor path for them.
static int dExtSpc_CreateHeapCB(fopAc_ac_c* i_ac) {
    daSpcItem01_c* i_this = (daSpcItem01_c*)i_ac;
    const dExtSpc_wwRow_t* row = dExtSpc_wwRow(i_this->m_itemNo);
    if (row == NULL) {
        return 0;
    }
    J3DModelData* modelData = dExtNpcMount_acquireModelData(row->fieldArc, row->bmdMember);
    if (modelData == NULL) {
        DuskLog.warn("[SpcItem01] §327 heap: '{}' member '{}' not resolvable (item {:#x})",
                     row->fieldArc, row->bmdMember, (int)i_this->m_itemNo);
        return 0;
    }
    // §327 modelflags 0x80000 + WW field-row J3D flags (0x11000022) — the same
    // pair the donor CreateItemHeap builds for a row with no anms/no chkFlag(4).
    i_this->mpModel = mDoExt_J3DModel__create(modelData, 0x80000, row->j3dFlags);
    i_this->mpBtkAnm = NULL;
    i_this->mpBpkAnm = NULL;
    i_this->mpBrkAnm = NULL;
    i_this->mpBckAnm = NULL;
    i_this->mpBtpAnm = NULL;
    return i_this->mpModel != NULL;
}

/* 8015DAF4-8015DBC0       .text set_mtx__13daSpcItem01_cFv */
void daSpcItem01_c::set_mtx() {
    csXyz angle = current.angle;
    cXyz scaleVec = scale;
    f32 offsetY = 0.0f;
    switch (m_itemNo) {
    case WWITEM_KNIGHTS_CREST_e:
        offsetY = -24.0f;
        break;
    }
    mpModel->setBaseScale(scaleVec);

    mDoMtx_stack_c::transS(current.pos.x, current.pos.y + offsetY, current.pos.z);
    mDoMtx_stack_c::ZXYrotM(angle);

    mpModel->setBaseTRMtx(mDoMtx_stack_c::get());
}

/* 8015DBC0-8015DBF4       .text _delete__13daSpcItem01_cFv */
BOOL daSpcItem01_c::_delete() {
    // §327 WW dItem_data::getFieldArc -> local WW subset row (arc may be absent
    // only if _create already failed; DeleteBase(NULL-safe arc) guarded).
    const dExtSpc_wwRow_t* row = dExtSpc_wwRow(m_itemNo);
    if (row == NULL) {
        return TRUE;
    }
    return DeleteBase(row->fieldArc);
}

/* 8015DBF4-8015DDD0       .text _create__13daSpcItem01_cFv */
cPhs_Step daSpcItem01_c::_create() {  // §327 cPhs_State -> cPhs_Step
    fopAcM_ct(this, daSpcItem01_c);

    m_itemNo = daSpcItem01_prm::getItemNo(this);
    // §327 dSv_event_flag_c::UNK_0E20 -> WWEV_UNK_0E20 (0x0E20, shims header);
    // the read routes to the DONOR flag block (route include above) — the ba1
    // Grandma port SETS this bit when she hands the shield over.
    if (m_itemNo == WWITEM_SHIELD_e && dComIfGs_isEventBit(WWEV_UNK_0E20)) {
        setLoadError();
        return cPhs_ERROR_e;
    }

    const dExtSpc_wwRow_t* row = dExtSpc_wwRow(m_itemNo);
    if (row == NULL) {
        // §327 NAMED DEBT (header banner): WW item number outside the local
        // subset — fail create CLEANLY, no improvised visuals.
        DuskLog.warn("[SpcItem01] §327 _create: WW item {:#x} outside the ported "
                     "dItem_data subset — placement skipped (named debt: full WW "
                     "dItem_data port)", (int)m_itemNo);
        setLoadError();
        return cPhs_ERROR_e;
    }

    // §327 donor: resLoad(getFieldArc) + entrySolidHeap(CheckFieldItemCreateHeap,
    // getHeapSize) — WW row values via the local subset; mPhs -> port mPhase.
    cPhs_Step phase_state = dComIfG_resLoad(&mPhase, row->fieldArc);
    if (phase_state == cPhs_COMPLEATE_e) {
        if (!fopAcM_entrySolidHeap(this, &dExtSpc_CreateHeapCB, row->heapSize)) {
            return cPhs_ERROR_e;
        }
        CreateInit();
    }

    return phase_state;
}

/* 8015DDD0-8015DF4C       .text CreateInit__13daSpcItem01_cFv */
BOOL daSpcItem01_c::CreateInit() {
    set_mtx();
    fopAcM_SetMtx(this, mpModel->getBaseTRMtx());
    mCcStts.Init(0, 0xFF, this);   // §327 port base name: mStts -> mCcStts
    mCcCyl.Set(l_cyl_src);         // §327 port base name: mCyl -> mCcCyl
    mCcCyl.SetStts(&mCcStts);
    f32 tempVar1 = (f32)getHeight();
    f32 tempVar2 = (f32)getR();
    if (scale.x > 1.0f) {
        tempVar1 *= scale.x;
        tempVar2 *= scale.x;
    }
    mCcCyl.SetR(tempVar2);
    mCcCyl.SetH(tempVar1);
    mAcchCir.SetWall(30.0f, 30.0f);
    // §327 port dBgS_ObjAcch::Set arity (+2 trailing NULL — toripost recipe).
    mAcch.Set(fopAcM_GetPosition_p(this), fopAcM_GetOldPosition_p(this), this, 1, &mAcchCir, fopAcM_GetSpeed_p(this), NULL, NULL);

    field_0x644 = daSpcItem01_prm::getFlag(this);
    fopAcM_SetGravity(this, -4.0f);
    switch ((s8)m_itemNo) {
    case WWITEM_SHIELD_e:
        scale.x = 1.5f;
        scale.y = 1.5f;
        scale.z = 1.5f;
        current.angle.x = 4000;
        current.angle.y = 4200;
        current.angle.z = 5200;
        fopAcM_SetGravity(this, 0.0f);
        break;
    }

    return TRUE;
}

/* 8015DF4C-8015DFE8       .text _execute__13daSpcItem01_cFv */
BOOL daSpcItem01_c::_execute() {
    eyePos = current.pos;
    attention_info.position = current.pos;
    m_timer++;
    set_effect();
    scale_anim();
    anim_play();
    move();
    rotate_item();
    setCol();
    set_mtx();
    return TRUE;
}

/* 8015DFE8-8015E070       .text set_effect__13daSpcItem01_cFv */
void daSpcItem01_c::set_effect() {
    // §327 WW dItem_data::checkAppearEffect/getAppearEffect -> local WW subset
    // (SHIELD row: effect_info == ID_SCENE_END pair -> branch inert-faithful).
    if (cLib_checkBit(field_0x644, (u16)0x01) && dExtSpc_wwCheckAppearEffect(m_itemNo) && !field_0x642 && m_itemNo != WWITEM_KNIGHTS_CREST_e) {
        // §327 donor 2-arg setSimple -> port 7-arg (WW defaults explicit).
        dComIfGp_particle_setSimple(dExtSpc_wwGetAppearEffect(m_itemNo), &current.pos, 0xFF,
                                    g_whiteColor, g_whiteColor, 0, 0.0f);
    }
}

/* 8015E070-8015E0D8       .text scale_anim__13daSpcItem01_cFv */
void daSpcItem01_c::scale_anim() {
    if (isRupee(m_itemNo)) {
        cLib_chaseF(&scale.x, 1.0f, 0.05f);
        cLib_chaseF(&scale.y, 1.0f, 0.05f);
        cLib_chaseF(&scale.z, 1.0f, 0.05f);
    }
}

/* 8015E0D8-8015E11C       .text anim_play__13daSpcItem01_cFv */
void daSpcItem01_c::anim_play() {
    f32 animPlayParam = 1.0f;
    if (m_itemNo == WWITEM_KNIGHTS_CREST_e) {
        animPlayParam = 0.0f;
    }
    // §327 WW animPlay(brk1,brk2,btk1,btk2,bck) -> port animPlay(btk,bpk,bck,x,
    // brk,btp): the WW call is all-1.0 except BCK = animPlayParam; the remap
    // reproduces exactly that. (Inert for the covered rows — no anms are built.)
    animPlay(1.0f, 1.0f, animPlayParam, 1.0f, 1.0f, 1.0f);
}

/* 8015E11C-8015E20C       .text move__13daSpcItem01_cFv */
void daSpcItem01_c::move() {
    fopAcM_posMoveF(this, mCcStts.GetCCMoveP());  // §327 mStts -> mCcStts
    mAcch.CrrPos(dComIfG_Bgsp());                 // §327 reference form (toripost recipe)
    switch (m_itemNo) {
    case WWITEM_SHIELD_e:
        break;
    case WWITEM_JOY_PENDANT_e:
        if (mAcch.ChkGroundLanding()) {
            speed.x = 0.0f;
            speed.y = 0.0f;
            speed.z = 0.0f;
            speedF = 0.0f;
        }
        break;
    default:
        if (mAcch.ChkGroundLanding()) {
            field_0x642 += 1;
            f32 newGravity = field_0x63C * 0.62f;
            if (newGravity > gravity - 0.5f) {
                speedF = 0.0f;
            } else {
                speed.x = 0.0f;
                speed.y = -newGravity;
                speed.z = 0.0f;
            }
        }
        break;
    }

    if (speed.y != 0.0f) {
        field_0x63C = speed.y;
    }
}

/* 8015E20C-8015E278       .text rotate_item__13daSpcItem01_cFv */
void daSpcItem01_c::rotate_item() {
    if (isRupee(m_itemNo)) {
        if (field_0x642 == 0) {
            field_0x640 = current.angle.x + 0x2000;
        } else {
            field_0x640 = 0;
        }
        cLib_chaseAngleS(&current.angle.x, field_0x640, 0x2000);
    }
}

/* 8015E278-8015E27C       .text setCol__13daSpcItem01_cFv */
void daSpcItem01_c::setCol() {
    /* Empty Function */
}

/* 8015E27C-8015E2A8       .text _draw__13daSpcItem01_cFv */
BOOL daSpcItem01_c::_draw() {
    return DrawBase();
}

/* 8015E2A8-8015E368       .text setTevStr__13daSpcItem01_cFv */
void daSpcItem01_c::setTevStr() {
    // §327 dKy_getEnvlight() -> g_env_light (port accessor; toripost recipe).
    if (m_itemNo == WWITEM_KNIGHTS_CREST_e) {
    // §406: WW feeder (donor type) — see d_kankyo_ww.h; TP never writes TevColor/TevKColor.
        dKyWw_settingTevStruct(TEV_TYPE_BG1, &current.pos, &tevStr);
    } else {
    // §406: WW feeder (donor type) — see d_kankyo_ww.h; TP never writes TevColor/TevKColor.
        dKyWw_settingTevStruct(TEV_TYPE_ACTOR, &current.pos, &tevStr);
    }
    dKyWw_setLightTevColorType(mpModel, &tevStr);

    // §327 donor loops mpModelArrow[2] here (WW itembase arrow-bundle doubles).
    // The port's TP itembase has no arrow-model member and no covered WW row is
    // an arrow bundle — loop dropped (named-debt scope, header banner).
}

/* 8015E368-8015E388       .text daSpcItem01_Draw__FP13daSpcItem01_c */
static BOOL daSpcItem01_Draw(daSpcItem01_c* i_this) {
    return i_this->_draw();
}

/* 8015E388-8015E3A8       .text daSpcItem01_Execute__FP13daSpcItem01_c */
static BOOL daSpcItem01_Execute(daSpcItem01_c* i_this) {
    return i_this->_execute();
}

/* 8015E3A8-8015E3B0       .text daSpcItem01_IsDelete__FP13daSpcItem01_c */
static BOOL daSpcItem01_IsDelete(daSpcItem01_c* ignored) {
    return TRUE;
}

/* 8015E3B0-8015E3D0       .text daSpcItem01_Delete__FP13daSpcItem01_c */
static BOOL daSpcItem01_Delete(daSpcItem01_c* i_this) {
    return i_this->_delete();
}

/* 8015E3D0-8015E3F0       .text daSpcItem01_Create__FP10fopAc_ac_c */
static cPhs_Step daSpcItem01_Create(fopAc_ac_c* i_this) {  // §327 cPhs_State -> cPhs_Step
    return ((daSpcItem01_c*)i_this)->_create();
}

static actor_method_class l_daSpcItem01_Method = {
    (process_method_func)daSpcItem01_Create,
    (process_method_func)daSpcItem01_Delete,
    (process_method_func)daSpcItem01_Execute,
    (process_method_func)daSpcItem01_IsDelete,
    (process_method_func)daSpcItem01_Draw,
};

actor_process_profile_definition g_profile_SPC_ITEM01 = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_SPC_ITEM01_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daSpcItem01_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_SPC_ITEM01_e,  // §327 donor slot absent -> port E_RD slot
    /* Actor SubMtd */ &l_daSpcItem01_Method,
    /* Status       */ fopAcStts_NOCULLEXEC_e | fopAcStts_CULL_e | fopAcStts_UNK4000_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_0_e,
};
